authors:
  carlo:
    name: Carlo Paris
    description: Autor
    avatar: avatars/cp_avatar.jpg
  filip: 
    name: Filip Reščić
    description: Autor
    avatar: avatars/fr_avatar.jpg
  team:
    name: Peripatetika
    description: Carlo & Filip
    avatar: images/favicon.png   