authors:
  carlo:
    name: Carlo Paris
    description: Osnivač
    avatar: avatari/cp_avatar.jpg
  filip: 
    name: Filip Reščić
    description: Osnivač
    avatar: avatari/cp_avatar.jpg
  team:
    name: Peripatetika Team
    description: Tim Peripatetike
    avatar: avatari/bullseye.jpg   