authors:
  carlo:
    name: Carlo Paris
    description: Osnivač
    avatar: avatari/cp_avatar.jpg
  filip: 
    name: Filip Reščić
    description: Osnivač
    avatar: https://github.com/squidfunk.png  